name: fitness
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_database: ^10.5.5
  animate_do: ^3.3.4
  iconsax_flutter: ^1.0.0
  intl: ^0.19.0
  shimmer: ^2.0.0
  flutter_staggered_grid_view: ^0.4.0
  iconsax: ^0.0.8
  dio: ^4.0.0
  url_launcher: ^6.0.12
  concentric_transition: ^1.0.1
  odometer: ^2.1.0
  vertical_card_pager: ^1.5.0
  loading_indicator: ^3.0.2
  flutter_youtube_view: ^2.0.2
  flutter_verification_code: ^1.1.0
  liquid_swipe: ^2.1.0
  intl_phone_number_input: ^0.7.0+2
  elastic_drawer: ^2.0.1
  bouncing_widget: ^2.0.0
  bottom_navy_bar: ^6.0.0
  salomon_bottom_bar: ^3.1.0
  avatar_glow: ^2.0.2
  carousel_slider: ^4.0.0
  google_fonts: ^6.2.1
  fl_chart: ^0.40.2
  connectivity: ^3.0.6
  firebase_storage: ^11.7.5
  image_picker: ^0.8.4+3
  shared_preferences: ^2.0.7
  onesignal_flutter: ^5.2.0
  syncfusion_flutter_datepicker: ^25.2.5
  table_calendar: ^3.0.0 
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/images/
   - android/app/src/main/res/mipmap-xxxhdpi/logo_1.jpg