// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsBxPRMtaYTAPgtkb06B5LZXab1ar2CNM',
    appId: '1:745685792016:web:5dfb5e0746898e1b186195',
    messagingSenderId: '745685792016',
    projectId: 'fitness-36602',
    authDomain: 'fitness-36602.firebaseapp.com',
    storageBucket: 'fitness-36602.appspot.com',
    measurementId: 'G-70G5VLCSM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIXd3eQ1GQKI4ticj21ELwo945n6opuqU',
    appId: '1:745685792016:android:76c34b66e4a23d45186195',
    messagingSenderId: '745685792016',
    projectId: 'fitness-36602',
    storageBucket: 'fitness-36602.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnEnS4g331GSS6GMsEdt1LZQYSjbkJaVo',
    appId: '1:745685792016:ios:e16cb9455178cc1c186195',
    messagingSenderId: '745685792016',
    projectId: 'fitness-36602',
    storageBucket: 'fitness-36602.appspot.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnEnS4g331GSS6GMsEdt1LZQYSjbkJaVo',
    appId: '1:745685792016:ios:e16cb9455178cc1c186195',
    messagingSenderId: '745685792016',
    projectId: 'fitness-36602',
    storageBucket: 'fitness-36602.appspot.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsBxPRMtaYTAPgtkb06B5LZXab1ar2CNM',
    appId: '1:745685792016:web:72ff7a6ef947b8d2186195',
    messagingSenderId: '745685792016',
    projectId: 'fitness-36602',
    authDomain: 'fitness-36602.firebaseapp.com',
    storageBucket: 'fitness-36602.appspot.com',
    measurementId: 'G-C1YHBLW8R1',
  );
}
